### ISSUE TITLE
epic: full IPv6 support

### ISSUE THREAD

**Issue by awoimbee** [Trow-Registry/trow#362]
* [ ] check if the ecosystem (containerd) supports IPv6 refs (or find workaround via DNS ?)
* [ ] update the [image ref regexes](https://github.com/Trow-Registry/trow/blob/665bdca2d3afd69bbf28db5990b09afe31b134e0/trow-server/src/image.rs#L15) to handle IPv6 refs ([see](https://github.com/distribution/distribution/pull/3489))
* [ ] CI test with trow listening on `::`
* [ ] helm: option to listen on `::`

Note that Trow will either listen on `0.0.0.0` or `::`, but not both.
See https://github.com/Trow-Registry/trow/issues/333
